version: "2.3.3"

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-service
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ../app/logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:latest
    container_name: loki-service
    ports:
      - 3100:3100
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - loki
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-service
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  
